# Generated by Django 5.0.7 on 2024-08-15 15:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Квартиры, апартаменты', 'Квартиры, апартаменты'), ('Дома, коттеджи', 'Дома, коттеджи'), ('Комнаты', 'Комнаты'), ('Апарт-отели', 'Апарт-отели'), ('Отели, гостиницы', 'Отели, гостиницы'), ('Мини-гостиницы', 'Мини-гостиницы'), ('Гостевые дома', 'Гостевые дома'), ('Глэмпинги, базы отдыха', 'Глэмпинги, базы отдыха'), ('Хостелы', 'Хостелы'), ('Студии', 'Студии')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('bedrooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bathrooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=255)),
                ('amenities', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renting.houseoffer')),
            ],
        ),
    ]
