# Generated by Django 5.0.7 on 2024-08-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_remove_houseoffer_amenities_alter_houseimages_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseImages',
            new_name='HouseImage',
        ),
    ]
